### ISSUE TITLE
Rename output files for wind and thermo versions

### ISSUE THREAD

**Issue by johnmauff** [mmbell/samurai#78]

**Comment by cenamiller** [comment]
Need the output files to include something like '_wind_' or '_w_' and/or '_thermo_' or '_tr_' to indicate their contents. 

currently named things like: samurai_XYZ_analysis

Will also need to modify how the file names are read in

**Comment by mmbell** [comment]
The original naming convention was designed as samurai_MODE_OUTPUT, where the two available modes were XYZ or RTZ for Cartesian or cylindrical geometry. The OUTPUT is either background, analysis, or increment (=analysis-background). One solution may be to expand the convention to be samurai_GEOMETRY_MODE_OUTPUT where current available geometries are now XYZ or RTZ and the modes are wind and thermo. I was corresponding with @tingyucha  and we are thinking that we should have a separate geometry mode for RHI scanning that is distinct from RTZ since they are similar but have different curvature terms. So then we could add “RHI” as a geometry that could ultimately work with either wind or thermo modes. APAR will have unique RHI and even more complex geometry capabilities in the future so this naming convention could allow for varying combinations.

**Comment by cenamiller** [comment]
Thanks Michael! Since we're just focusing on cartesian for the V3 thermo deliverable, my understanding is that the new supported formats should be:

samurai_XYZ_wind_analysis
samurai_XYZ_tr_analysis

samurai_XYZ_wind_background
samurai_XYZ_tr_background

samurai_XYZ_wind_increment
samurai_XYZ_tr_increment

samurai_RTZ _wind_analysis
samurai_RTZ _wind_background
samurai_RTZ _wind_increment

But we should implement it in the code in a way that makes sense to also support these formats in the future:

samurai_RTZ_tr_analysis
samurai_RTZ_tr_background
samurai_RTZ_tr_increment

samurai_RHI_wind_analysis
samurai_RHI_tr_analysis

samurai_RHI_wind_background
samurai_RHI_tr_background

samurai_RHI_wind_increment
samurai_RHI_tr_increment

**Comment by mmbell** [comment]
Yes, I think that all makes sense. I am OK with ‘tr’ as the name, but am
thinking it should be consistent with whatever mode name we have in the
code. I believe that is ‘thermo’ correct? I think we should be
consistent with either tr or thermo throughout. Maybe we should add
another parameter for geometry and keep mode option separate so we can
mix and match, but throw an error if a user tries to run an unsupported
mode.


On August 8, 2024, Github Notifications ***@***.***>
wrote:
> Thanks Michael! Since we're just focusing on cartesian for the V3
> thermo deliverable, my understanding is that the new supported formats
> should be:
>
> samurai_XYZ_wind_analysis
>  samurai_XYZ_tr_analysis
>
> samurai_XYZ_wind_background
>  samurai_XYZ_tr_background
>
> samurai_XYZ_wind_increment
>  samurai_XYZ_tr_increment
>
> samurai_RTZ _wind_analysis
>  samurai_RTZ _wind_background
>  samurai_RTZ _wind_increment
>
> But we should implement it in the code in a way that makes sense to
> also support these formats in the future:
>
> samurai_RTZ_tr_analysis
>  samurai_RTZ_tr_background
>  samurai_RTZ_tr_increment
>
> samurai_RHI_wind_analysis
>  samurai_RHI_tr_analysis
>
> samurai_RHI_wind_background
>  samurai_RHI_tr_background
>
> samurai_RHI_wind_increment
>  samurai_RHI_tr_increment
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mmbell/samurai/issues/78#issuecomment-2275975734>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAEONF7JJNQCJAWQ47FOXG3ZQN6E5AVCNFSM6AAAAABLI6EE5SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZVHE3TKNZTGQ>.
You are receiving this because you commented.Message ID:
***@***.***>
